# Berlin Wastewater Dashboard
# Copyright (c) 2025 Alexandra von Criegern
# Licensed under the ISC License.

name: Fetch new data

on:
  schedule:
    - cron: "0 6 * * *" # Runs daily at 06:00 UTC
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Install dependencies
        run: npm ci

      - name: Run fetch script
        run: node scripts/fetchLiveData.js

      - name: Validate fetched data
        run: node tests/validate/validateForChart.js

      - name: Build site
        run: npm run build

      - name: Serve built site locally
        run: npx serve dist -l 4173 &

      - name: Wait for preview server to be ready
        run: npx wait-on http://localhost:4173

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run UI tests with Playwright
        run: npm run test:chart

      - name: Commit and push updated data
        env:
          GH_TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
        run: |
          git config user.name "Alexandra von Criegern"
          git config user.email "plutonik@gmx.net"
          git pull --rebase origin main
          git add public/data/data.json
          git diff --quiet --cached || git commit -m "chore(data): update from latest API fetch"
          git push https://x-access-token:$GH_TOKEN@github.com/${{ github.repository }} HEAD:main
